/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module fullmix(din, dout);
  input [15:0] din;
  wire [15:0] din;
  output [15:0] dout;
  wire [15:0] dout;
  wire [3:0] _00_;
  wire [3:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [3:0] w0;
  wire [3:0] w1;
  wire [3:0] w2;
  wire [3:0] w3;
  assign _00_[0] = din[0] ^ din[12];
  assign _00_[1] = din[1] ^ din[13];
  assign _00_[2] = din[2] ^ din[14];
  assign _00_[3] = din[3] ^ din[15];
  assign dout[0] = _00_[0] ^ din[8];
  assign dout[1] = _00_[1] ^ din[9];
  assign dout[2] = _00_[2] ^ din[10];
  assign dout[3] = _00_[3] ^ din[11];
  assign _01_[0] = din[4] ^ din[0];
  assign _01_[1] = din[5] ^ din[1];
  assign _01_[2] = din[6] ^ din[2];
  assign _01_[3] = din[7] ^ din[3];
  assign dout[4] = _01_[0] ^ din[12];
  assign dout[5] = _01_[1] ^ din[13];
  assign dout[6] = _01_[2] ^ din[14];
  assign dout[7] = _01_[3] ^ din[15];
  assign _02_[0] = din[8] ^ din[4];
  assign _02_[1] = din[9] ^ din[5];
  assign _02_[2] = din[10] ^ din[6];
  assign _02_[3] = din[11] ^ din[7];
  assign dout[8] = _02_[0] ^ din[0];
  assign dout[9] = _02_[1] ^ din[1];
  assign dout[10] = _02_[2] ^ din[2];
  assign dout[11] = _02_[3] ^ din[3];
  assign _03_[0] = din[12] ^ din[8];
  assign _03_[1] = din[13] ^ din[9];
  assign _03_[2] = din[14] ^ din[10];
  assign _03_[3] = din[15] ^ din[11];
  assign dout[12] = _03_[0] ^ din[4];
  assign dout[13] = _03_[1] ^ din[5];
  assign dout[14] = _03_[2] ^ din[6];
  assign dout[15] = _03_[3] ^ din[7];
  assign w3 = din[3:0];
  assign w2 = din[7:4];
  assign w1 = din[11:8];
  assign w0 = din[15:12];
endmodule

module quartet_round_logic(din, rk, dout);
  input [15:0] din;
  wire [15:0] din;
  input [3:0] rk;
  wire [3:0] rk;
  output [15:0] dout;
  wire [15:0] dout;
  wire [15:0] mid;
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  assign mid[0] = s3[0] ^ rk[0];
  assign mid[1] = s3[1] ^ rk[1];
  assign mid[2] = s3[2] ^ rk[2];
  assign mid[3] = s3[3] ^ rk[3];
  assign mid[4] = s2[0] ^ rk[0];
  assign mid[5] = s2[1] ^ rk[1];
  assign mid[6] = s2[2] ^ rk[2];
  assign mid[7] = s2[3] ^ rk[3];
  assign mid[8] = s1[0] ^ rk[0];
  assign mid[9] = s1[1] ^ rk[1];
  assign mid[10] = s1[2] ^ rk[2];
  assign mid[11] = s1[3] ^ rk[3];
  assign mid[12] = s0[0] ^ rk[0];
  assign mid[13] = s0[1] ^ rk[1];
  assign mid[14] = s0[2] ^ rk[2];
  assign mid[15] = s0[3] ^ rk[3];
  fullmix fm (
    .din(mid),
    .dout(dout)
  );
  sbox4_logic s0i (
    .a(din[15:12]),
    .y(s0)
  );
  sbox4_logic s1i (
    .a(din[11:8]),
    .y(s1)
  );
  sbox4_logic s2i (
    .a(din[7:4]),
    .y(s2)
  );
  sbox4_logic s3i (
    .a(din[3:0]),
    .y(s3)
  );
endmodule

module sbox4_logic(a, y);
  input [3:0] a;
  wire [3:0] a;
  output [3:0] y;
  wire [3:0] y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire t1;
  wire t2;
  wire t3;
  wire t4;
  wire t5;
  wire t6;
  wire t7;
  wire t8;
  wire t9;
  wire x0;
  wire x1;
  wire x2;
  wire x3;
  assign t1 = a[0] & a[1];
  assign t2 = a[0] & a[2];
  assign t3 = a[0] & a[3];
  assign t4 = a[1] & a[2];
  assign t5 = a[1] & a[3];
  assign t6 = a[2] & a[3];
  assign t7 = t1 & a[2];
  assign t8 = t1 & a[3];
  assign t9 = t2 & a[3];
  assign _02_ = a[0] ^ a[2];
  assign _03_ = _02_ ^ t4;
  assign y[0] = _03_ ^ a[3];
  assign _04_ = a[1] ^ a[3];
  assign _05_ = _04_ ^ t5;
  assign _06_ = _05_ ^ t6;
  assign _07_ = _06_ ^ t7;
  assign _08_ = _07_ ^ t8;
  assign y[1] = _08_ ^ t9;
  assign _09_ = _00_ ^ a[3];
  assign _10_ = _09_ ^ t1;
  assign _11_ = _10_ ^ t3;
  assign _12_ = _11_ ^ t5;
  assign _13_ = _12_ ^ t8;
  assign y[2] = _13_ ^ t9;
  assign _14_ = _01_ ^ a[1];
  assign _15_ = _14_ ^ a[3];
  assign _16_ = _15_ ^ t4;
  assign _17_ = _16_ ^ t7;
  assign _18_ = _17_ ^ t8;
  assign y[3] = _18_ ^ t9;
  assign _01_ = ~a[0];
  assign _00_ = ~a[2];
  assign x3 = a[3];
  assign x2 = a[2];
  assign x1 = a[1];
  assign x0 = a[0];
endmodule
